### ISSUE TITLE
uiautomation sample

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-samples-rs#20]
It appears that CoInitializeEx does not need a CoUninitialize. Is this hidden then?

**Comment by kennykerr** [comment]
It's not hidden. If you'd like to call `CoUninitialize` you're certainly free to do that. 

In my experience, there is very rarely a good reason to call `CoUninitialize` on an MTA as it is almost impossible to do reliably. Process termination is far better at cleaning things up.
