### ISSUE TITLE
`core_app`-sample error messages

### ISSUE THREAD

**Issue by Ericvf** [microsoft/windows-samples-rs#24]
When running the `core_app` sample I get the following message from the Debug Console:

- The Application Object must initially be accessed from the multi-thread apartment.

So I tried using the WinRT crate to call ` RoInitialize` w/ `RO_INIT_MULTITHREADED`:

```rs
fn main() -> Result<()> {
    winrt::init_apartment(winrt::ApartmentType::MTA); // <-- Added

    let app: IFrameworkViewSource = CoreApp().into();
    CoreApplication::Run(app)?;
    Ok(())
}
```

However I am getting the following error:

-  The parameter is incorrect.

```CallContext:[\AppRunOrActivateView] 
onecoreuap\shell\coreapplication\application\lib\coreapplicationfactory.cpp(147)\twinapi.appcore.dll!00007FFFE54CFD88: (caller: 00007FF758902A45) ReturnHr(10) tid(4ae4) 80070057 The parameter is incorrect.
Error: Error { code: 0x80070057, message: "serverName", win32_code: 87 }
```

Any tip on how to get this running? Do I need to install additional bits?
Thanks

My system specs
```
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0
```

**Comment by riverar** [comment]
Did you also run `register.cmd` to get the packaged application registered?

**Comment by Ericvf** [comment]
As as matter of fact I did. 

Just when I thought I tested this thoroughly I now discover that it actually works if you run `register.cmd` with Administrator privileges (duh) AND if you start the UWP App via the start menu. Running the executable binary directly or running `cargo run` doesn't work. This may be expected behavior for now. So I apologize :)

One thing I did notice is that `register` has an invalid path at the last statement. Perhaps someone can fix this minor issue in a following commit.

**Comment by riverar** [comment]
@Ericvf Great, glad this was resolved. One note, you shouldn't need to run as Administator to register that package. (You do need to enable sideloading via Developer Settings and start your app via Start.) Perhaps a quick readme is in order.
